apiVersion: apps/v1
kind: Deployment
metadata:
  name: dicom-adapter-export
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dicom-adapter-export
  template:
    metadata:
      labels:
        app: dicom-adapter-export
    spec:
      containers:
        - name: dicom-adapter-export
          image: gcr.io/cloud-healthcare-containers/healthcare-api-dicom-dicomweb-adapter-export:0.2.43
          args:
            - "--peer_dimse_aet=PEER_AET"
            - "--peer_dimse_ip=PEER_IP"
            - "--peer_dimse_port=PEER_PORT"
            - "--project_id=PROJECT_ID"
            - "--subscription_id=PUBSUB_SUBSCRIPTION_ID"
            - "--dicomweb_addr=https://healthcare.googleapis.com/v1/projects/PROJECT_ID/locations/LOCATION/datasets/DATASET_ID/dicomStores/DICOM_STORE_ID/dicomWeb"
            - "--oauth_scopes=https://www.googleapis.com/auth/pubsub"
