apiVersion: apps/v1
kind: Deployment
metadata:
  name: dicom-adapter-import
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dicom-adapter-import
  template:
    metadata:
      labels:
        app: dicom-adapter-import
    spec:
      containers:
        - name: dicom-adapter-import
          image: gcr.io/cloud-healthcare-containers/healthcare-api-dicom-dicomweb-adapter-import:0.2.43
          ports:
            - containerPort: 2575
              protocol: TCP
              name: "port"
          args:
            - "--dimse_aet=IMPORTADAPTER"
            - "--dimse_port=2575"
            - "--dicomweb_address=https://healthcare.googleapis.com/v1/projects/PROJECT_ID/locations/LOCATION/datasets/DATASET_ID/dicomStores/DICOM_STORE_ID/dicomWeb"
          env:
          - name: ENV_AETS_JSON
            valueFrom:
              configMapKeyRef:
                name: aet-dictionary
                key: AETs.json
