apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dicom-adapter-import
  name: dicom-adapter-import
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: dicom-adapter-import
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dicom-adapter-import
    spec:
      containers:
      - args:
        - --dimse_aet=IMPORTADAPTER
        - --dimse_port=2575
        - --dicomweb_address=https://healthcare.googleapis.com/v1/projects/PROJECT/locations/REGIONdatasets/DATASET/dicomStores/STORE/dicomWeb
        image: gcr.io/cloud-healthcare-containers/healthcare-api-dicom-dicomweb-adapter-import:0.2.29
        imagePullPolicy: IfNotPresent
        name: dicom-import-adapter
        ports:
        - containerPort: 2575
          name: port
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
